<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <p>Using <b>catch</b> to display an error.</p>
    <p id="result"></p>
    <br>
    <hr>
    <p>throw, try & catch with input validation</p>
    <p>Enter any number between 6 to 10, not less or more than that and also alphabets are not accepted. <br> Dont believe me then try it </p>

    <input type="text" id="demo">
    <button type="button" onclick="myFun()">Test My Input</button>
    <p id="result1"></p>
    <br>
    <hr>
    <p>throw, try, catch & finally with input validation</p>
    <p>Enter any number between 6 to 10, not less or more than that and also alphabets are not accepted. <br> Dont believe me then try it </p>

    <input type="text" id="demo1">
    <button type="button" onclick="myFun1()">Test My Input</button>
    <p id="result2"></p>
    <br>
    <hr>
    <p>

        RangeError Example : <br>
        let num = 1; <br>
        try { <br>
            num.toPrecision(500); <br>
        } <br>
        catch(error) { <br>
            document.getElementById("result3").innerHTML = error.name; <br>
        }

    </p>
    <p id="result3"></p>
    <br>
    <hr>
    <p>

        ReferenceError Example : <br>
        let x = 5; <br>
        try { <br>
            x = y + 1; <br>
        } <br>
        catch(error) { <br>
            document.getElementById("result4").innerHTML = error.name; <br>
        }

    </p>
    <p id="result4"></p>
    <br>
    <hr>
    <p>

        SyntaxError Example : <br>
        try { <br>
            eval("alert('Hello)"); <br>
        } <br>
            catch(error) { <br>
            document.getElementById("result5").innerHTML = error.name; <br>
        }

    </p>
    <p id="result5"></p>
    <br>
    <hr>
    <p>

        TypeError Example : <br>
        let numb = 1; <br>
        try { <br>
            numb.toUpperCase(); <br>
        } <br>
        catch(error) { <br>
            document.getElementById("demo").innerHTML = error.name; <br>
        }

    </p>
    <p id="result6"></p>

    <script>

    // The try statement allows you to define a block of code to be tested for errors while it is being executed.
    // The catch statement allows you to define a block of code to be executed, if an error occurs in the try block.

        try {
            adddddddlery("Oi, welcome");
        } 
        catch(error) {
            document.getElementById("result").innerHTML = error.message;
        }


    // If we use throw together with try and catch, we can control program flow and generate custom error messages.

        function myFun() {
            const msg = document.getElementById("result1");
            msg.innerHTML = "";

            let x = document.getElementById("demo").value; // .value - input field me enter kiye hue input ka value lega 

            try{
                if(x.trim() == "") throw "empty";
                if(isNaN(x)) throw "not a number";

                x = Number(x);

                if(x < 5) throw "too low";
                if(x > 10) throw "too high";
            }
            catch(error) {
                msg.innerHTML = "Input is " + error;
            }
        }


    //The finally statement lets us execute code, after try and catch, regardless of the result
        function myFun1() {
            const msg = document.getElementById("result2");
            msg.innerHTML = "";

            let x = document.getElementById("demo1").value; // .value - input field me enter kiye hue input ka value lega 

            try{
                if(x.trim() == "") throw "empty";
                if(isNaN(x)) throw "not a number";

                x = Number(x);

                if(x < 5) throw "too low";
                if(x > 10) throw "too high";
            }
            catch(error) {
                msg.innerHTML = "Input is " + error;
            }
            finally {
                document.getElementById("demo1").value = "";
            }
        }

    // JavaScript has a built in error object that provides error information when an error occurs
    // Error Name Values
        // Six different values can be returned by the error name property:

            // Error Name	        Description
            // EvalError	        An error has occurred in the eval() function
            // RangeError	        A number "out of range" has occurred
            // ReferenceError	    An illegal reference has occurred
            // SyntaxError	        A syntax error has occurred
            // TypeError	        A type error has occurred
            // URIError	            An error in encodeURI() has occurred


        // RangeError
        let num = 1;
        try {
            num.toPrecision(500);
        }
        catch(error) {
            document.getElementById("result3").innerHTML = error.name;
        }


        // ReferenceError
        let x = 5;
        try {
            x = y + 1;
        }
        catch(err) {
            document.getElementById("result4").innerHTML = err.name;
        }


        // SyntaxError
        try {
            eval("alert('Hello)");
        }
            catch(error) {
            document.getElementById("result5").innerHTML = error.name;
        }


        // TypeError
        let numb = 1;
        try {
            numb.toUpperCase();
        }
        catch(error) {
            document.getElementById("result6").innerHTML = error.name;
        }

    </script>
</body>
</html>